export default projects = [
  {
    _id: new ObjectId('686f9fb50a97e2b28a106a5e'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/Food_order.png?tr=w-300,h-288,fo-top"',
    title: 'Food Ordering and Delivery',
    Category_Badge: 'E-Commerce(B2C)',
    Tech_Stack_Badges: ['React js', 'Nodejs', 'Express js', 'python', 'nosql'],
    category: 'ecommerce',
    __v: 0,
    projectId: 1,
  },
  {
    _id: new ObjectId('686f9fb50a97e2b28a106a5f'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/Custom_Project.png?tr=w-300,h-288,fo-top"',
    title: 'Customized Products',
    Category_Badge: 'E-Commerce(B2C)',
    Tech_Stack_Badges: ['React js', 'Nodejs', 'Express js', 'java', 'Mongodb'],
    category: 'ecommerce',
    __v: 0,
    projectId: 2,
  },
  {
    _id: new ObjectId('686f9fb50a97e2b28a106a58'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/Online_Fashion_store.png?tr=w-300,h-288,fo-top',
    title: 'Online Fashion Store',
    Category_Badge: 'E-Commerce(B2C)',
    Tech_Stack_Badges: [
      'javascript',
      'Nodejs',
      'Express js',
      'Tailwindcss',
      'Mongodb',
    ],
    category: 'ecommerce',
    __v: 0,
    projectId: 3,
  },
  {
    _id: new ObjectId('686f9fb50a97e2b28a106a61'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/Niche_Product_Store.png?tr=w-300,h-288,fo-top',
    title: 'Niche Product Store',
    Category_Badge: 'E-Commerce(B2C)',
    Tech_Stack_Badges: [
      'javascript',
      'Nodejs',
      'Express js',
      'Tailwindcss',
      'Mongodb',
    ],
    category: 'ecommerce',
    __v: 0,
    projectId: 4,
  },
  {
    _id: new ObjectId('686f9fb50a97e2b28a106a63'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/Business_Dashboards/marketing_dashboard.png?tr=w-300,h-288,fo-top',
    title: 'Marketing Dashboard',
    Category_Badge: 'Business Dashboards',
    Tech_Stack_Badges: ['Connect Google Analytics API (optional)'],
    category: 'business',
    __v: 0,
    projectId: 5,
  },
  {
    _id: new ObjectId('686f9fb50a97e2b28a106a64'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/Business_Dashboards/HR_dashboard.png?tr=w-300,h-288,fo-top',
    title: 'HR Dashboard(Employee Analytics)',
    Category_Badge: 'Business Dashboards',
    Tech_Stack_Badges: [
      'Progress bars for goals',
      'Table filter for employee list',
    ],
    category: 'business',
    __v: 0,
    projectId: 6,
  },
  {
    _id: new ObjectId('686f9fb50a97e2b28a106a67'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/Business_Dashboards/Project_Management_Dashboard.png?tr=w-300,h-288,fo-top',
    title: 'Project Management Dashboard',
    Category_Badge: 'Business Dashboards',
    Tech_Stack_Badges: [
      'Drag and drop task management (Kanban board style)',
      'Deadline warnings',
    ],
    category: 'business',
    __v: 0,
    projectId: 7,
  },
  {
    _id: new ObjectId('686f9fb50a97e2b28a106a65'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/Business_Dashboards/Finance%20Dashboard%20Overview.png?tr=w-300,h-288,fo-top',
    title: 'Finance Dashboard',
    Category_Badge: 'Business Dashboards',
    Tech_Stack_Badges: [
      'Monthly expense vs income chart',
      'Category-wise expense pie chart',
    ],
    category: 'business',
    __v: 0,
    projectId: 8,
  },
  {
    _id: new ObjectId('686f9fb50a97e2b28a106a69'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/Business_Dashboards/E-commerce_Business_Dashboard.png?tr=w-300,h-288,fo-top',
    title: 'E-commerce Business Dashboard',
    Category_Badge: 'Business Dashboards',
    Tech_Stack_Badges: [
      'Total orders, total revenue, returning vs new customers',
      'Graphs by product category',
    ],
    category: 'business',
    __v: 0,
    projectId: 9,
  },
  {
    _id: new ObjectId('686f9fb50a97e2b28a106a5b'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/Second-Hand-Marketplace.png?tr=w-300,h-288,fo-top',
    title: 'Second-Hand Marketplace',
    Category_Badge: 'E-Commerce(C2C)',
    Tech_Stack_Badges: [
      'React js',
      'Nodejs',
      'javascript',
      'python',
      'Mongodb',
    ],
    category: 'ecommerce',
    __v: 0,
    projectId: 10,
  },
  {
    _id: new ObjectId('686f9fb50a97e2b28a106a68'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/Business_Dashboards/customer_support_dashboard.png?tr=w-300,h-288,fo-top',
    title: 'Customer Support Dashboard',
    Category_Badge: 'Business Dashboards',
    Tech_Stack_Badges: [
      'Number of open vs closed tickets',
      'Customer satisfaction ratings',
    ],
    category: 'business',
    __v: 0,
    projectId: 11,
  },
  {
    _id: new ObjectId('686f9fb50a97e2b28a106a5c'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/Digital_Product.png?tr=w-300,h-288,fo-top',
    title: 'Digital Product Store',
    Category_Badge: 'E-Commerce (C2C or B2C)',
    Tech_Stack_Badges: ['React js', 'Nodejs', 'Express js', 'java', 'Mongodb'],
    category: 'ecommerce',
    __v: 0,
    projectId: 12,
  },
  {
    _id: new ObjectId('686f9fb50a97e2b28a106a5d'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/Multivender_market_place.png?tr=w-300,h-288,fo-top',
    title: 'Multi-Vendor Marketplace',
    Category_Badge: 'E-Commerce(B2C + C2C)',
    Tech_Stack_Badges: ['Nodejs', 'Express js', 'java', 'mysql'],
    category: 'ecommerce',
    __v: 0,
    projectId: 13,
  },
  {
    _id: new ObjectId('686f9fb50a97e2b28a106a62'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/Business_Dashboards/sales_dashboard.png?tr=w-300,h-288,fo-top',
    title: 'Sales Dashboard',
    Category_Badge: 'Business Dashboards',
    Tech_Stack_Badges: ['React js', 'Recharts/Chart.js', 'Tailwindcss'],
    category: 'business',
    __v: 0,
    projectId: 14,
  },
  {
    _id: new ObjectId('686f9fb50a97e2b28a106a66'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/Business_Dashboards/Inventory%20Management%20Dashboard%20Overview.png?tr=w-300,h-288,fo-top',
    title: ' Inventory Management Dashboard',
    Category_Badge: 'Business Dashboards',
    Tech_Stack_Badges: [
      'Stock levels (with warnings for low stock)',
      'Inventory aging report',
    ],
    category: 'business',
    __v: 0,
    projectId: 15,
  },
  {
    _id: new ObjectId('686f9fb50a97e2b28a106a59'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/Grocery_Delivery_Website.png?tr=w-300,h-288,fo-top',
    title: 'Grocery Delivery Website',
    Category_Badge: 'E-Commerce(B2C)',
    Tech_Stack_Badges: ['React js', 'Nodejs', 'Express js', 'java', 'Mongodb'],
    category: 'ecommerce',
    __v: 0,
    projectId: 16,
  },
  {
    _id: new ObjectId('686f9fb50a97e2b28a106a5a'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/Electronics_Store.png?tr=w-300,h-288,fo-top',
    title: 'Electronics Store',
    Category_Badge: 'E-Commerce(B2B)',
    Tech_Stack_Badges: [
      'React js',
      'Tailwindcss',
      'Express js',
      'python',
      'Mongodb',
    ],
    category: 'ecommerce',
    __v: 0,
    projectId: 17,
  },
  {
    _id: new ObjectId('686f9fb50a97e2b28a106a60'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/Rental_Marketplace.png?tr=w-300,h-288,fo-top',
    title: 'Rental Marketplace',
    Category_Badge: 'E-Commerce(C2C)',
    Tech_Stack_Badges: [
      'React js',
      'Tailwindcss',
      'Express js',
      'python',
      'Mongodb',
    ],
    category: 'ecommerce',
    __v: 0,
    projectId: 18,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4d4'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/IOT/smart_Home_Automation_system.png?tr=w-300,h-288,fo-top',
    title: 'Smart Home Automation System',
    Category_Badge: 'IOT',
    Tech_Stack_Badges: ['ESP32', 'WiFi', 'Relay Module '],
    category: 'IOT',
    __v: 0,
    projectId: 19,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4d5'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/IOT/AI_based_weather_station.png?tr=w-300,h-288,fo-top',
    title: 'IoT-Based Weather Station',
    Category_Badge: 'IOT',
    Tech_Stack_Badges: ['BMP180 sensor', 'ESP32', 'Firebase/ThingSpeak'],
    category: 'IOT',
    __v: 0,
    projectId: 20,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4d6'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/IOT/smart_plant_monitoring_system.png?tr=w-300,h-288,fo-top',
    title: 'Smart Plant Monitoring System',
    Category_Badge: 'IOT',
    Tech_Stack_Badges: ['ESP32', 'Soil moisture', 'temp sensor'],
    category: 'IOT',
    __v: 0,
    projectId: 21,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4d7'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/IOT/smart_garbage_monitoring_system.png?tr=w-300,h-288,fo-top',
    title: 'Smart Garbage Monitoring (Smart Bin)',
    Category_Badge: 'IOT',
    Tech_Stack_Badges: [
      ' Ultrasonic Sensor',
      'ESP32',
      'Web dashboard with Google Maps API',
    ],
    category: 'IOT',
    __v: 0,
    projectId: 22,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4d8'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/IOT/air_quality_monitoring_system.png?tr=w-300,h-288,fo-top',
    title: 'IoT-Based Air Quality Monitoring System',
    Category_Badge: 'IOT',
    Tech_Stack_Badges: ['MQ135 gas sensor', 'OLED', 'ESP32'],
    category: 'IOT',
    __v: 0,
    projectId: 23,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4d9'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/IOT/smart_door_lock_system.png?tr=w-300,h-288,fo-top',
    title: 'Smart Door Lock System',
    Category_Badge: 'IOT',
    Tech_Stack_Badges: ['Servo', 'RFID reader', 'ESP32'],
    category: 'IOT',
    __v: 0,
    projectId: 24,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4da'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/IOT/parking_management.png?tr=w-300,h-288,fo-top',
    title: 'IoT Parking Management System',
    Category_Badge: 'IOT',
    Tech_Stack_Badges: ['ESP32', 'IR sensor', 'Show slot status on web UI'],
    category: 'IOT',
    __v: 0,
    projectId: 25,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4db'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/IOT/industrial_equipment_monitoring_system.png?tr=w-300,h-288,fo-top',
    title: 'Industrial Equipment Monitoring System',
    Category_Badge: 'IOT',
    Tech_Stack_Badges: ['Vibration Sensor', 'Temp sensor', ' ESP32'],
    category: 'IOT',
    __v: 0,
    projectId: 26,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4dc'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/IOT/smart_helmet_for_riders.png?tr=w-300,h-288,fo-top',
    title: 'IoT Smart Helmet for Riders',
    Category_Badge: 'IOT',
    Tech_Stack_Badges: ['GPS', 'GSM', 'Accelerometer', 'ESP32'],
    category: 'IOT',
    __v: 0,
    projectId: 27,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4dd'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/IOT/Pet_activity_feeding_tracker.png?tr=w-300,h-288,fo-top',
    title: 'Pet Activity & Feeding Tracker',
    Category_Badge: 'IOT',
    Tech_Stack_Badges: ['ESP32', 'WiFi', 'cloud history'],
    category: 'IOT',
    __v: 0,
    projectId: 28,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4de'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/AI_ML/AI_Image_caption.png?tr=w-300,h-288,fo-top',
    title: 'AI Image Caption Generator',
    Category_Badge: 'AI/ML Web App',
    Tech_Stack_Badges: ['React js', 'API:image-to-text model'],
    category: 'AI_ML',
    __v: 0,
    projectId: 29,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4df'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/AI_ML/Fake_news_detections.png?tr=w-300,h-288,fo-top',
    title: 'Fake News Detection',
    Category_Badge: 'AI/ML Web App',
    Tech_Stack_Badges: [
      'Flask or Node.js',
      'Trained on fake news dataset (like LIAR, Kaggle)',
    ],
    category: 'AI_ML',
    __v: 0,
    projectId: 30,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4e0'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/AI_ML/AI_Powered_Resume_analyser.png?tr=w-300,h-288,fo-top',
    title: 'AI Resume Analyzer',
    Category_Badge: 'AI/ML Web App',
    Tech_Stack_Badges: [
      'Python backend with spaCy or GPT API',
      'Frontend with drag-drop file uploader',
    ],
    category: 'AI_ML',
    __v: 0,
    projectId: 31,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4e1'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/AI_ML/AI_chatbot.png?tr=w-300,h-288,fo-top',
    title: ' AI Chatbot / Virtual Assistant',
    Category_Badge: 'AI/ML Web App',
    Tech_Stack_Badges: ['React+Tailwind', 'GPT API / custom model'],
    category: 'AI_ML',
    __v: 0,
    projectId: 32,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4e2'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/AI_ML/Mood_classifire.png?tr=w-300,h-288,fo-top',
    title: 'AI Music Mood Classifier',
    Category_Badge: 'AI/ML Web App',
    Tech_Stack_Badges: ['Audio analysis with Python + ML', 'React frontend'],
    category: 'AI_ML',
    __v: 0,
    projectId: 33,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4e3'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/AI_ML/Ml_based_desisess_prediction.png?tr=w-300,h-288,fo-top',
    title: 'Machine Learning-Based Disease Predictor',
    Category_Badge: 'AI/ML Web App',
    Tech_Stack_Badges: [
      'Trained on Disease dataset',
      'Backend ML + React frontend',
    ],
    category: 'AI_ML',
    __v: 0,
    projectId: 34,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4e4'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/AI_ML/Ml_based_House_Prise_Pridictor.png?tr=w-300,h-288,fo-top',
    title: 'ML-based House Price Predictor',
    Category_Badge: 'AI/ML Web App',
    Tech_Stack_Badges: [
      'ML model (scikit-learn)',
      'React + Chart.js for visuals',
    ],
    category: 'AI_ML',
    __v: 0,
    projectId: 35,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4e5'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/AI_ML/AI_based_CodeReview.png?tr=w-300,h-288,fo-top',
    title: 'AI-Based Code Reviewer',
    Category_Badge: 'AI/ML Web App',
    Tech_Stack_Badges: ['Use GPT-4 or CodeT5 models'],
    category: 'AI_ML',
    __v: 0,
    projectId: 36,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4e6'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/AI_ML/Face_expression_detection.png?tr=w-300,h-288,fo-top',
    title: 'Face Expression Detection (Webcam)',
    Category_Badge: 'AI/ML Web App',
    Tech_Stack_Badges: [
      'TensorFlow.js (runs in browser)',
      'React + useRef for webcam',
    ],
    category: 'AI_ML',
    __v: 0,
    projectId: 37,
  },
  {
    _id: new ObjectId('6877662fd4a75290fbf4a4e7'),
    image_url:
      'https://ik.imagekit.io/someimages12/images/AI_ML/AI_powered_E_learning.png?tr=w-300,h-288,fo-top',
    title: 'AI-Powered E-Learning Assistant',
    Category_Badge: 'AI/ML Web App',
    Tech_Stack_Badges: ['LangChain + OpenAI + PDF parser', 'React UI'],
    category: 'AI_ML',
    __v: 0,
    projectId: 38,
  },
];
