/* const laptop = [
  {
    "productName": "HP Omen 16 Gaming Laptop",
    "brand": "HP",
    "modelNumber": "Omen16-b1350TX",
    "category": "Laptop",
    "purpose": "Gaming",
    "price": 129999,
    "discountPrice": 114999,
    "processor": "Intel Core i7-12700H (12th Gen)",
    "ram": "16GB DDR5",
    "storage": "1TB PCIe NVMe SSD",
    "gpu": "NVIDIA GeForce RTX 3060 (6GB)",
    "display": "16.1-inch QHD, 165Hz",
    "batteryLife": "6 hours",
    "os": "Windows 11 Home",
    "weight": "2.4 kg",
    "ports": "HDMI, USB-C, 3x USB 3.2, RJ45, Audio Jack",
    "warranty": "1 Year",
    "description": "High-performance gaming laptop with 12th Gen Intel CPU and RTX 3060 GPU for smooth 1440p gaming.",
    "availability": "In stock",
    "installationRequired": false,
    "technicianBookingAvailable": true,
    "images": ["url1", "url2", "url3"]
  },
  {
    "productName": "Dell XPS 15 Professional Laptop",
    "brand": "Dell",
    "modelNumber": "XPS9520",
    "category": "Laptop",
    "purpose": "Professional",
    "price": 174999,
    "discountPrice": 159999,
    "processor": "Intel Core i7-12700H",
    "ram": "16GB DDR5",
    "storage": "1TB SSD",
    "gpu": "NVIDIA RTX 3050 Ti (4GB)",
    "display": "15.6-inch OLED 3.5K Touch Display",
    "batteryLife": "8 hours",
    "os": "Windows 11 Pro",
    "weight": "1.9 kg",
    "ports": "2x Thunderbolt 4, USB-C, SD Reader",
    "warranty": "1 Year",
    "description": "Premium business-class laptop with vivid OLED display, suitable for developers and professionals.",
    "availability": "In stock",
    "installationRequired": false,
    "technicianBookingAvailable": true,
    "images": ["url1", "url2", "url3"]
  },
  {
    "productName": "Lenovo Legion 5 Pro",
    "brand": "Lenovo",
    "modelNumber": "Legion5Pro-82RG00G7IN",
    "category": "Laptop",
    "purpose": "Gaming",
    "price": 149999,
    "discountPrice": 134999,
    "processor": "AMD Ryzen 7 6800H",
    "ram": "16GB DDR5",
    "storage": "1TB SSD",
    "gpu": "NVIDIA RTX 3070 Ti 8GB",
    "display": "16-inch WQXGA 165Hz",
    "batteryLife": "7 hours",
    "os": "Windows 11 Home",
    "weight": "2.45 kg",
    "ports": "USB-C, HDMI, Ethernet, 4x USB-A",
    "warranty": "1 Year",
    "description": "Powerful gaming laptop with Ryzen 6000 series processor and RTX 3070 Ti for high-end performance.",
    "availability": "In stock",
    "installationRequired": false,
    "technicianBookingAvailable": true,
    "images": ["url1", "url2", "url3"]
  },
  {
    "productName": "Apple MacBook Air M2",
    "brand": "Apple",
    "modelNumber": "M2-2023",
    "category": "Laptop",
    "purpose": "Professional",
    "price": 139900,
    "discountPrice": 129900,
    "processor": "Apple M2 Chip (8-core CPU, 10-core GPU)",
    "ram": "8GB Unified Memory",
    "storage": "512GB SSD",
    "gpu": "Integrated",
    "display": "13.6-inch Liquid Retina",
    "batteryLife": "18 hours",
    "os": "macOS Sonoma",
    "weight": "1.24 kg",
    "ports": "2x Thunderbolt 3, MagSafe 3",
    "warranty": "1 Year",
    "description": "Slim and efficient laptop for professional and creative work with Apple’s M2 chip.",
    "availability": "In stock",
    "installationRequired": false,
    "technicianBookingAvailable": false,
    "images": ["url1", "url2", "url3"]
  },
  {
    "productName": "Asus ROG Strix G16",
    "brand": "ASUS",
    "modelNumber": "G614JV-N4128W",
    "category": "Laptop",
    "purpose": "Gaming",
    "price": 159999,
    "discountPrice": 144999,
    "processor": "Intel Core i9-13980HX",
    "ram": "32GB DDR5",
    "storage": "1TB SSD",
    "gpu": "NVIDIA RTX 4070 8GB",
    "display": "16-inch FHD+ 165Hz",
    "batteryLife": "6 hours",
    "os": "Windows 11 Home",
    "weight": "2.5 kg",
    "ports": "HDMI, USB-C, Ethernet, 3x USB-A",
    "warranty": "1 Year",
    "description": "Next-gen gaming laptop with 13th Gen Intel CPU and RTX 4070 GPU for smooth AAA performance.",
    "availability": "In stock",
    "installationRequired": false,
    "technicianBookingAvailable": true,
    "images": ["url1", "url2", "url3"]
  },
  {
    "productName": "Acer Aspire 7",
    "brand": "Acer",
    "modelNumber": "A715-76G",
    "category": "Laptop",
    "purpose": "Development",
    "price": 68999,
    "discountPrice": 62999,
    "processor": "Intel Core i5-12450H",
    "ram": "16GB DDR4",
    "storage": "512GB SSD",
    "gpu": "NVIDIA GTX 1650 4GB",
    "display": "15.6-inch FHD 144Hz",
    "batteryLife": "7 hours",
    "os": "Windows 11 Home",
    "weight": "2.1 kg",
    "ports": "HDMI, USB-C, 3x USB-A, LAN",
    "warranty": "1 Year",
    "description": "Ideal laptop for developers with 12th Gen Intel processor and solid GPU performance.",
    "availability": "In stock",
    "installationRequired": false,
    "technicianBookingAvailable": true,
    "images": ["url1", "url2", "url3"]
  },
  {
    "productName": "MSI Modern 15",
    "brand": "MSI",
    "modelNumber": "Modern15-B12M",
    "category": "Laptop",
    "purpose": "Professional",
    "price": 61999,
    "discountPrice": 58999,
    "processor": "Intel Core i5-1235U",
    "ram": "16GB DDR4",
    "storage": "512GB SSD",
    "gpu": "Integrated Intel Iris Xe",
    "display": "15.6-inch FHD IPS",
    "batteryLife": "8 hours",
    "os": "Windows 11 Home",
    "weight": "1.7 kg",
    "ports": "HDMI, 3x USB-A, USB-C",
    "warranty": "1 Year",
    "description": "Lightweight business laptop built for productivity and professional use.",
    "availability": "In stock",
    "installationRequired": false,
    "technicianBookingAvailable": false,
    "images": ["url1", "url2", "url3"]
  },
  {
    "productName": "Samsung Galaxy Book3 Pro",
    "brand": "Samsung",
    "modelNumber": "NP940XFG-KC1IN",
    "category": "Laptop",
    "purpose": "Professional",
    "price": 154999,
    "discountPrice": 139999,
    "processor": "Intel Core i7-1360P",
    "ram": "16GB LPDDR5",
    "storage": "1TB SSD",
    "gpu": "Intel Iris Xe",
    "display": "14-inch 3K AMOLED",
    "batteryLife": "19 hours",
    "os": "Windows 11 Home",
    "weight": "1.17 kg",
    "ports": "2x Thunderbolt 4, HDMI, USB-A",
    "warranty": "1 Year",
    "description": "Ultra-thin premium laptop with stunning AMOLED display and all-day battery life.",
    "availability": "In stock",
    "installationRequired": false,
    "technicianBookingAvailable": false,
    "images": ["url1", "url2", "url3"]
  },
  {
    "productName": "Realme Book Prime",
    "brand": "Realme",
    "modelNumber": "RMNB2101",
    "category": "Laptop",
    "purpose": "Educational",
    "price": 49999,
    "discountPrice": 45999,
    "processor": "Intel Core i5-11320H",
    "ram": "8GB LPDDR4x",
    "storage": "512GB SSD",
    "gpu": "Intel Iris Xe",
    "display": "14-inch 2K IPS",
    "batteryLife": "10 hours",
    "os": "Windows 11 Home",
    "weight": "1.37 kg",
    "ports": "2x USB-C, 1x USB-A, 1x Headphone Jack",
    "warranty": "1 Year",
    "description": "Slim and affordable laptop designed for students and light office work.",
    "availability": "In stock",
    "installationRequired": false,
    "technicianBookingAvailable": false,
    "images": ["url1", "url2", "url3"]
  },
  {
    "productName": "Infinix INBook X2 Plus",
    "brand": "Infinix",
    "modelNumber": "INBookX2Plus-i7",
    "category": "Laptop",
    "purpose": "Educational",
    "price": 58999,
    "discountPrice": 54999,
    "processor": "Intel Core i7-1195G7",
    "ram": "16GB LPDDR4x",
    "storage": "512GB SSD",
    "gpu": "Intel Iris Xe",
    "display": "15.6-inch FHD IPS",
    "batteryLife": "10 hours",
    "os": "Windows 11 Home",
    "weight": "1.58 kg",
    "ports": "2x USB-C, 2x USB-A, HDMI, Audio Jack",
    "warranty": "1 Year",
    "description": "Budget-friendly laptop ideal for learning and lightweight work with strong specs.",
    "availability": "In stock",
    "installationRequired": false,
    "technicianBookingAvailable": false,
    "images": ["url1", "url2", "url3"]
  }
]

const desktop = [
  {
    "productName": "HP Pavilion Gaming Desktop TG01",
    "brand": "HP",
    "modelNumber": "TG01-2006in",
    "category": "Desktop",
    "purpose": "Gaming",
    "price": 84999,
    "discountPrice": 76999,
    "processor": "AMD Ryzen 5 5600G",
    "ram": "16GB DDR4",
    "storage": "1TB HDD + 512GB SSD",
    "gpu": "NVIDIA GeForce GTX 1660 Super 6GB",
    "os": "Windows 11 Home",
    "powerSupply": "500W Bronze Certified",
    "ports": "4x USB 3.2, HDMI, DisplayPort, Ethernet, Audio Jack",
    "warranty": "1 Year",
    "description": "Compact gaming desktop with Ryzen 5 processor and GTX 1660 Super GPU for smooth 1080p gaming.",
    "availability": "In stock",
    "installationRequired": true,
    "technicianBookingAvailable": true,
    "images": ["url1", "url2", "url3"]
  },
  {
    "productName": "Lenovo IdeaCentre 5 Desktop",
    "brand": "Lenovo",
    "modelNumber": "90RW00ANIN",
    "category": "Desktop",
    "purpose": "Professional",
    "price": 61999,
    "discountPrice": 57999,
    "processor": "Intel Core i5-12400",
    "ram": "8GB DDR4",
    "storage": "512GB SSD",
    "gpu": "Integrated Intel UHD Graphics 730",
    "os": "Windows 11 Home",
    "powerSupply": "380W",
    "ports": "USB 3.2, USB-C, HDMI, Ethernet, Audio Out",
    "warranty": "1 Year",
    "description": "Modern compact desktop ideal for office, development, and productivity use.",
    "availability": "In stock",
    "installationRequired": true,
    "technicianBookingAvailable": true,
    "images": ["url1", "url2", "url3"]
  },
  {
    "productName": "ASUS ROG Strix GA15 Gaming Desktop",
    "brand": "ASUS",
    "modelNumber": "GA15DK-R5600X3060",
    "category": "Desktop",
    "purpose": "Gaming",
    "price": 124999,
    "discountPrice": 114999,
    "processor": "AMD Ryzen 5 5600X",
    "ram": "16GB DDR4",
    "storage": "512GB SSD + 1TB HDD",
    "gpu": "NVIDIA RTX 3060 12GB",
    "os": "Windows 11 Home",
    "powerSupply": "700W 80+ Gold",
    "ports": "USB-C, HDMI, DisplayPort, Audio In/Out",
    "warranty": "1 Year",
    "description": "Powerful gaming desktop with RTX 3060 for smooth 1440p gaming and multitasking.",
    "availability": "In stock",
    "installationRequired": true,
    "technicianBookingAvailable": true,
    "images": ["url1", "url2", "url3"]
  },
  {
    "productName": "Dell Inspiron 3910 Tower Desktop",
    "brand": "Dell",
    "modelNumber": "3910-i512400",
    "category": "Desktop",
    "purpose": "Professional",
    "price": 67999,
    "discountPrice": 62999,
    "processor": "Intel Core i5-12400",
    "ram": "16GB DDR4",
    "storage": "512GB SSD + 1TB HDD",
    "gpu": "Intel UHD Graphics 730",
    "os": "Windows 11 Home",
    "powerSupply": "400W",
    "ports": "USB 3.2, HDMI, VGA, LAN",
    "warranty": "1 Year",
    "description": "Dependable tower desktop designed for productivity and multitasking in office environments.",
    "availability": "In stock",
    "installationRequired": true,
    "technicianBookingAvailable": true,
    "images": ["url1", "url2", "url3"]
  },
  {
    "productName": "Apple Mac Mini M2",
    "brand": "Apple",
    "modelNumber": "MMFJ3HN/A",
    "category": "Desktop",
    "purpose": "Professional",
    "price": 69900,
    "discountPrice": 67900,
    "processor": "Apple M2 Chip (8-core CPU, 10-core GPU)",
    "ram": "8GB Unified Memory",
    "storage": "256GB SSD",
    "gpu": "Integrated",
    "os": "macOS Sonoma",
    "powerSupply": "150W Internal PSU",
    "ports": "2x Thunderbolt 4, HDMI, Ethernet, USB-A",
    "warranty": "1 Year",
    "description": "Ultra-compact desktop powered by Apple M2 chip for creative and software development workloads.",
    "availability": "In stock",
    "installationRequired": false,
    "technicianBookingAvailable": false,
    "images": ["url1", "url2", "url3"]
  },
  {
    "productName": "Acer Aspire TC-1780 Tower Desktop",
    "brand": "Acer",
    "modelNumber": "TC-1780",
    "category": "Desktop",
    "purpose": "Educational",
    "price": 49999,
    "discountPrice": 46999,
    "processor": "Intel Core i3-13100",
    "ram": "8GB DDR4",
    "storage": "512GB SSD",
    "gpu": "Intel UHD 730",
    "os": "Windows 11 Home",
    "powerSupply": "350W",
    "ports": "HDMI, USB 3.2, USB 2.0, Ethernet",
    "warranty": "1 Year",
    "description": "Budget desktop PC ideal for students and home study use.",
    "availability": "In stock",
    "installationRequired": true,
    "technicianBookingAvailable": true,
    "images": ["url1", "url2", "url3"]
  },
  {
    "productName": "MSI MAG Infinite S3",
    "brand": "MSI",
    "modelNumber": "MAG-S3-12TC",
    "category": "Desktop",
    "purpose": "Gaming",
    "price": 119999,
    "discountPrice": 108999,
    "processor": "Intel Core i7-12700F",
    "ram": "16GB DDR4",
    "storage": "1TB SSD",
    "gpu": "NVIDIA RTX 3060 12GB",
    "os": "Windows 11 Home",
    "powerSupply": "600W 80+ Bronze",
    "ports": "HDMI, DisplayPort, USB-C, USB 3.2",
    "warranty": "1 Year",
    "description": "Powerful gaming PC with advanced cooling and high-speed components.",
    "availability": "In stock",
    "installationRequired": true,
    "technicianBookingAvailable": true,
    "images": ["url1", "url2", "url3"]
  },
  {
    "productName": "Zotac MEK Hero G1",
    "brand": "Zotac",
    "modelNumber": "G1-R7-3070",
    "category": "Desktop",
    "purpose": "Gaming",
    "price": 139999,
    "discountPrice": 129999,
    "processor": "AMD Ryzen 7 5800X",
    "ram": "16GB DDR4",
    "storage": "1TB SSD",
    "gpu": "NVIDIA GeForce RTX 3070 8GB",
    "os": "Windows 11 Home",
    "powerSupply": "750W 80+ Gold",
    "ports": "HDMI, DisplayPort, USB-C, 4x USB-A",
    "warranty": "1 Year",
    "description": "High-end gaming PC ready for 2K gaming and multitasking.",
    "availability": "In stock",
    "installationRequired": true,
    "technicianBookingAvailable": true,
    "images": ["url1", "url2", "url3"]
  },
  {
    "productName": "Intel NUC 12 Pro Mini PC",
    "brand": "Intel",
    "modelNumber": "NUC12WSHi5",
    "category": "Desktop",
    "purpose": "Professional",
    "price": 58999,
    "discountPrice": 54999,
    "processor": "Intel Core i5-1240P",
    "ram": "16GB DDR4",
    "storage": "512GB SSD",
    "gpu": "Intel Iris Xe",
    "os": "Windows 11 Pro",
    "powerSupply": "120W External Adapter",
    "ports": "2x Thunderbolt 4, HDMI, Ethernet, USB 3.2",
    "warranty": "1 Year",
    "description": "Compact and powerful mini PC suitable for business, office, or developer environments.",
    "availability": "In stock",
    "installationRequired": false,
    "technicianBookingAvailable": true,
    "images": ["url1", "url2", "url3"]
  },
  {
    "productName": "Custom Assembled Desktop - Developer Build",
    "brand": "Custom",
    "modelNumber": "DEV-BUILD-001",
    "category": "Desktop",
    "purpose": "Development",
    "price": 94999,
    "discountPrice": 89999,
    "processor": "Intel Core i7-12700K",
    "ram": "32GB DDR4",
    "storage": "1TB NVMe SSD",
    "gpu": "NVIDIA GTX 1660 Super 6GB",
    "os": "Windows 11 Pro",
    "powerSupply": "650W 80+ Bronze",
    "ports": "4x USB 3.2, HDMI, DisplayPort, LAN, Audio",
    "warranty": "1 Year (Custom Build)",
    "description": "Developer-focused PC for coding, simulation, and multitasking with strong performance balance.",
    "availability": "In stock",
    "installationRequired": true,
    "technicianBookingAvailable": true,
    "images": ["url1", "url2", "url3"]
  }
]


const mobile = [
    {
  "productId": "MOB001",
  "name": "Apple iPhone 15 Pro Max",
  "brand": "Apple",
  "category": "Smartphone",
  "subcategory": "Flagship",
  "processor": "Apple A17 Pro chip (3nm)",
  "ram": "8GB",
  "storage": "256GB",
  "battery": "4422mAh",
  "display": "6.7-inch Super Retina XDR OLED (2796x1290)",
  "camera": "48MP + 12MP + 12MP rear, 12MP front",
  "os": "iOS 17",
  "network": "5G, 4G LTE, Wi-Fi 6E, Bluetooth 5.3",
  "price": 149999,
  "warranty": "1 Year Apple Warranty",
  "weight": "221g",
  "colorOptions": ["Natural Titanium", "Blue Titanium", "White Titanium", "Black Titanium"],
  "availability": "In Stock",
  "imageUrls": ["https://example.com/images/iphone15promax.jpg"]
},
{
  "productId": "MOB002",
  "name": "Samsung Galaxy S24 Ultra",
  "brand": "Samsung",
  "category": "Smartphone",
  "subcategory": "Flagship",
  "processor": "Snapdragon 8 Gen 3 for Galaxy",
  "ram": "12GB",
  "storage": "512GB",
  "battery": "5000mAh with 45W fast charging",
  "display": "6.8-inch QHD+ Dynamic AMOLED 2X, 120Hz",
  "camera": "200MP + 12MP + 10MP + 10MP rear, 12MP front",
  "os": "Android 14, One UI 6",
  "network": "5G, Wi-Fi 7, Bluetooth 5.3",
  "price": 139999,
  "warranty": "1 Year Samsung Warranty",
  "weight": "233g",
  "colorOptions": ["Titanium Gray", "Titanium Violet", "Titanium Black"],
  "availability": "In Stock",
  "imageUrls": ["https://example.com/images/s24ultra.jpg"]
},
{
  "productId": "MOB003",
  "name": "OnePlus 12",
  "brand": "OnePlus",
  "category": "Smartphone",
  "subcategory": "Flagship",
  "processor": "Snapdragon 8 Gen 3",
  "ram": "16GB",
  "storage": "512GB",
  "battery": "5400mAh, 100W SuperVOOC",
  "display": "6.82-inch 120Hz AMOLED QHD+",
  "camera": "50MP + 64MP + 48MP rear, 32MP front",
  "os": "OxygenOS 14 (Android 14)",
  "network": "5G, Wi-Fi 7, Bluetooth 5.4",
  "price": 79999,
  "warranty": "1 Year Manufacturer Warranty",
  "weight": "220g",
  "colorOptions": ["Flowy Emerald", "Silky Black"],
  "availability": "In Stock",
  "imageUrls": ["https://example.com/images/oneplus12.jpg"]
},
{
  "productId": "MOB004",
  "name": "Google Pixel 8 Pro",
  "brand": "Google",
  "category": "Smartphone",
  "subcategory": "Flagship",
  "processor": "Google Tensor G3",
  "ram": "12GB",
  "storage": "256GB",
  "battery": "5050mAh, 30W fast charging",
  "display": "6.7-inch LTPO OLED, 120Hz, QHD+",
  "camera": "50MP + 48MP + 48MP rear, 10.5MP front",
  "os": "Android 14 (Pixel UI)",
  "network": "5G, Wi-Fi 7, Bluetooth 5.3",
  "price": 106999,
  "warranty": "1 Year Manufacturer Warranty",
  "weight": "213g",
  "colorOptions": ["Porcelain", "Obsidian", "Bay Blue"],
  "availability": "In Stock",
  "imageUrls": ["https://example.com/images/pixel8pro.jpg"]
},
{
  "productId": "MOB005",
  "name": "Xiaomi 14 Ultra",
  "brand": "Xiaomi",
  "category": "Smartphone",
  "subcategory": "Flagship Camera Phone",
  "processor": "Snapdragon 8 Gen 3",
  "ram": "16GB",
  "storage": "512GB",
  "battery": "5000mAh, 90W wired + 50W wireless",
  "display": "6.73-inch QHD+ AMOLED, 120Hz",
  "camera": "50MP Quad Leica Camera Setup",
  "os": "HyperOS (Android 14)",
  "network": "5G, Wi-Fi 7, Bluetooth 5.4",
  "price": 99999,
  "warranty": "1 Year Warranty",
  "weight": "224g",
  "colorOptions": ["Black", "White", "Blue"],
  "availability": "In Stock",
  "imageUrls": ["https://example.com/images/xiaomi14ultra.jpg"]
},
{
  "productId": "MOB006",
  "name": "Realme GT 6 Pro",
  "brand": "Realme",
  "category": "Smartphone",
  "subcategory": "Performance",
  "processor": "Snapdragon 8s Gen 3",
  "ram": "12GB",
  "storage": "256GB",
  "battery": "5200mAh, 120W SuperDart Charge",
  "display": "6.78-inch AMOLED, 144Hz",
  "camera": "50MP + 8MP + 2MP rear, 32MP front",
  "os": "Realme UI 5.0 (Android 14)",
  "network": "5G, Wi-Fi 6E, Bluetooth 5.3",
  "price": 49999,
  "warranty": "1 Year Warranty",
  "weight": "210g",
  "colorOptions": ["Racing Green", "Iron Black"],
  "availability": "In Stock",
  "imageUrls": ["https://example.com/images/realmegt6pro.jpg"]
},
{
  "productId": "MOB007",
  "name": "ASUS ROG Phone 8",
  "brand": "ASUS",
  "category": "Smartphone",
  "subcategory": "Gaming",
  "processor": "Snapdragon 8 Gen 3",
  "ram": "16GB",
  "storage": "512GB",
  "battery": "5500mAh, 65W fast charging",
  "display": "6.78-inch AMOLED 165Hz",
  "camera": "50MP + 13MP + 8MP rear, 32MP front",
  "os": "ROG UI (Android 14)",
  "network": "5G, Wi-Fi 7, Bluetooth 5.3",
  "price": 109999,
  "warranty": "1 Year Global Warranty",
  "weight": "239g",
  "colorOptions": ["Phantom Black", "Storm Gray"],
  "availability": "In Stock",
  "imageUrls": ["https://example.com/images/rogphone8.jpg"]
},
{
  "productId": "MOB008",
  "name": "Nothing Phone (2)",
  "brand": "Nothing",
  "category": "Smartphone",
  "subcategory": "Design Focused",
  "processor": "Snapdragon 8+ Gen 1",
  "ram": "12GB",
  "storage": "256GB",
  "battery": "4700mAh, 45W fast charging",
  "display": "6.7-inch OLED, 120Hz",
  "camera": "50MP + 50MP rear, 32MP front",
  "os": "Nothing OS 2.0 (Android 14)",
  "network": "5G, Wi-Fi 6, Bluetooth 5.3",
  "price": 49999,
  "warranty": "1 Year Warranty",
  "weight": "201g",
  "colorOptions": ["White", "Black", "Gray"],
  "availability": "In Stock",
  "imageUrls": ["https://example.com/images/nothingphone2.jpg"]
},
{
  "productId": "MOB009",
  "name": "Redmi Note 13 Pro+",
  "brand": "Redmi",
  "category": "Smartphone",
  "subcategory": "Mid-range",
  "processor": "MediaTek Dimensity 7200 Ultra",
  "ram": "12GB",
  "storage": "256GB",
  "battery": "5000mAh, 120W fast charging",
  "display": "6.67-inch AMOLED 120Hz",
  "camera": "200MP + 8MP + 2MP rear, 16MP front",
  "os": "MIUI 15 (Android 14)",
  "network": "5G, Wi-Fi 6, Bluetooth 5.3",
  "price": 29999,
  "warranty": "1 Year Warranty",
  "weight": "205g",
  "colorOptions": ["Fusion Purple", "Midnight Black"],
  "availability": "In Stock",
  "imageUrls": ["https://example.com/images/redminote13proplus.jpg"]
},
{
  "productId": "MOB010",
  "name": "Vivo V30 Pro",
  "brand": "Vivo",
  "category": "Smartphone",
  "subcategory": "Camera Centric",
  "processor": "MediaTek Dimensity 8200",
  "ram": "12GB",
  "storage": "256GB",
  "battery": "5000mAh, 80W FlashCharge",
  "display": "6.78-inch AMOLED, 120Hz",
  "camera": "50MP + 50MP + 12MP rear, 50MP front",
  "os": "Funtouch OS 14 (Android 14)",
  "network": "5G, Wi-Fi 6, Bluetooth 5.3",
  "price": 43999,
  "warranty": "1 Year Manufacturer Warranty",
  "weight": "186g",
  "colorOptions": ["Blue Green", "Black", "Purple"],
  "availability": "In Stock",
  "imageUrls": ["https://example.com/images/vivov30pro.jpg"]
}

]
 */

const Processors_CPUs = [
  {
    id: 'cpu001',
    name: 'Intel Core i9-13900K',
    brand: 'Intel',
    category: 'Processor & CPU',
    series: 'Core i9',
    generation: '13th Gen (Raptor Lake)',
    cores: 24,
    threads: 32,
    base_clock: '3.0 GHz',
    boost_clock: '5.8 GHz',
    cache: '36 MB Intel Smart Cache',
    socket: 'LGA 1700',
    integrated_gpu: 'Intel UHD Graphics 770',
    tdp: '125W',
    price: 62999,
    warranty: '3 Years',
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/processors_and_CPU/Intel%20Core%20i9-13900K.jpeg?updatedAt=1761832429636',
  },
  {
    id: 'cpu002',
    name: 'AMD Ryzen 9 7950X',
    brand: 'AMD',
    category: 'Processor & CPU',
    series: 'Ryzen 9',
    generation: '7000 Series',
    cores: 16,
    threads: 32,
    base_clock: '4.5 GHz',
    boost_clock: '5.7 GHz',
    cache: '80 MB',
    socket: 'AM5',
    integrated_gpu: 'Radeon Graphics',
    tdp: '170W',
    price: 59999,
    warranty: '3 Years',
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/processors_and_CPU/AMD%20Ryzen%209%207950X.jpg?updatedAt=1761832436315',
  },
  {
    id: 'cpu003',
    name: 'Intel Core i7-13700K',
    brand: 'Intel',
    category: 'Processor & CPU',
    series: 'Core i7',
    generation: '13th Gen (Raptor Lake)',
    cores: 16,
    threads: 24,
    base_clock: '3.4 GHz',
    boost_clock: '5.4 GHz',
    cache: '30 MB',
    socket: 'LGA 1700',
    integrated_gpu: 'Intel UHD Graphics 770',
    tdp: '125W',
    price: 42999,
    warranty: '3 Years',
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/processors_and_CPU/Intel%20Core%20i7-13700K.jpg?updatedAt=1761832969202',
  },
  {
    id: 'cpu004',
    name: 'AMD Ryzen 7 7800X3D',
    brand: 'AMD',
    category: 'Processor & CPU',
    series: 'Ryzen 7',
    generation: '7000 Series',
    cores: 8,
    threads: 16,
    base_clock: '4.2 GHz',
    boost_clock: '5.0 GHz',
    cache: '104 MB',
    socket: 'AM5',
    integrated_gpu: 'Radeon Graphics',
    tdp: '120W',
    price: 39999,
    warranty: '3 Years',
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/processors_and_CPU/AMD%20Ryzen%207%207800X3D.jpg?updatedAt=1761832429968',
  },
  {
    id: 'cpu005',
    name: 'Intel Core i5-13600K',
    brand: 'Intel',
    category: 'Processor & CPU',
    series: 'Core i5',
    generation: '13th Gen (Raptor Lake)',
    cores: 14,
    threads: 20,
    base_clock: '3.5 GHz',
    boost_clock: '5.1 GHz',
    cache: '24 MB',
    socket: 'LGA 1700',
    integrated_gpu: 'Intel UHD Graphics 770',
    tdp: '125W',
    price: 27999,
    warranty: '3 Years',
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/processors_and_CPU/Intel%20Core%20i5-13600K.jpg?updatedAt=1761832430424',
  },
  {
    id: 'cpu006',
    name: 'AMD Ryzen 5 7600X',
    brand: 'AMD',
    category: 'Processor & CPU',
    series: 'Ryzen 5',
    generation: '7000 Series',
    cores: 6,
    threads: 12,
    base_clock: '4.7 GHz',
    boost_clock: '5.3 GHz',
    cache: '38 MB',
    socket: 'AM5',
    integrated_gpu: 'Radeon Graphics',
    tdp: '105W',
    price: 22999,
    warranty: '3 Years',
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/processors_and_CPU/AMD%20Ryzen%205%207600X.jpg?updatedAt=1761832429911',
  },
  {
    id: 'cpu007',
    name: 'Intel Core i3-13100',
    brand: 'Intel',
    category: 'Processor & CPU',
    series: 'Core i3',
    generation: '13th Gen (Raptor Lake)',
    cores: 4,
    threads: 8,
    base_clock: '3.4 GHz',
    boost_clock: '4.5 GHz',
    cache: '12 MB',
    socket: 'LGA 1700',
    integrated_gpu: 'Intel UHD Graphics 730',
    tdp: '60W',
    price: 11999,
    warranty: '3 Years',
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/processors_and_CPU/Intel%20Core%20i3-13100.jpg?updatedAt=1761832429838',
  },
  {
    id: 'cpu008',
    name: 'Apple M2 Pro Chip',
    brand: 'Apple',
    category: 'Processor & CPU',
    series: 'Apple Silicon',
    generation: 'M2 Pro',
    cores: 12,
    threads: '—',
    base_clock: '—',
    boost_clock: '—',
    cache: '40 MB Unified Cache',
    socket: 'Soldered (SoC)',
    integrated_gpu: '19-core GPU',
    tdp: 'Variable',
    price: 89999,
    warranty: '1 Year',
    availability: 'Pre-installed only',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/processors_and_CPU/Apple%20M2%20Pro%20Chip.jpg?updatedAt=1761832430106',
  },
  {
    id: 'cpu009',
    name: 'AMD Ryzen Threadripper PRO 5995WX',
    brand: 'AMD',
    category: 'Processor & CPU',
    series: 'Threadripper PRO',
    generation: '5000 WX-Series',
    cores: 64,
    threads: 128,
    base_clock: '2.7 GHz',
    boost_clock: '4.5 GHz',
    cache: '288 MB',
    socket: 'sWRX8',
    integrated_gpu: 'No',
    tdp: '280W',
    price: 489999,
    warranty: '3 Years',
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/processors_and_CPU/AMD%20Ryzen%20Threadripper%20PRO%205995WX.jpg?updatedAt=1761832429926',
  },
  {
    id: 'cpu010',
    name: 'Intel Xeon W9-3495X',
    brand: 'Intel',
    category: 'Processor & CPU',
    series: 'Xeon W9',
    generation: 'Sapphire Rapids',
    cores: 56,
    threads: 112,
    base_clock: '1.9 GHz',
    boost_clock: '4.8 GHz',
    cache: '105 MB',
    socket: 'LGA 4677',
    integrated_gpu: 'No',
    tdp: '350W',
    price: 429999,
    warranty: '3 Years',
    availability: 'Limited Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/processors_and_CPU/Intel%20Xeon%20W9-3495X.jpg?updatedAt=1761832429797',
  },
];

const Motherboards = [
  {
    id: 'mb001',
    name: 'ASUS ROG STRIX Z790-E Gaming WiFi',
    brand: 'ASUS',
    category: 'Motherboard',
    socket: 'LGA 1700',
    chipset: 'Intel Z790',
    form_factor: 'ATX',
    supported_cpu: 'Intel 12th / 13th Gen',
    supported_ram: 'DDR5 up to 128GB',
    ram_slots: 4,
    max_ram_speed: '7800 MHz (OC)',
    pcie_slots: '1 x PCIe 5.0 x16, 2 x PCIe 4.0 x16',
    storage_support: '5 x M.2, 6 x SATA 6Gb/s',
    network: 'WiFi 6E + 2.5G LAN',
    usb_ports: 'USB 3.2 Gen 2x2, Type-C',
    audio: 'SupremeFX 7.1 Channel',
    price: 46999,
    warranty: '3 Years',
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Motherboards/ASUS%20ROG%20STRIX%20Z790-E%20Gaming%20WiFi.jpg?updatedAt=1761832375960',
  },
  {
    id: 'mb002',
    name: 'MSI MAG B650 TOMAHAWK WIFI',
    brand: 'MSI',
    category: 'Motherboard',
    socket: 'AM5',
    chipset: 'AMD B650',
    form_factor: 'ATX',
    supported_cpu: 'AMD Ryzen 7000 Series',
    supported_ram: 'DDR5 up to 128GB',
    ram_slots: 4,
    max_ram_speed: '6600 MHz (OC)',
    pcie_slots: '1 x PCIe 5.0 x16, 1 x PCIe 4.0 x16',
    storage_support: '2 x M.2, 4 x SATA 6Gb/s',
    network: 'WiFi 6 + 2.5G LAN',
    usb_ports: 'USB 3.2 Gen 2x2, Type-C',
    audio: 'Realtek ALC4080 7.1 HD Audio',
    price: 24999,
    warranty: '3 Years',
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Motherboards/MSI%20MAG%20B650%20TOMAHAWK%20WIFI.jpg?updatedAt=1761832378054',
  },
  {
    id: 'mb003',
    name: 'Gigabyte Z790 AORUS ELITE AX',
    brand: 'Gigabyte',
    category: 'Motherboard',
    socket: 'LGA 1700',
    chipset: 'Intel Z790',
    form_factor: 'ATX',
    supported_cpu: 'Intel 12th / 13th Gen',
    supported_ram: 'DDR5 up to 128GB',
    ram_slots: 4,
    max_ram_speed: '7600 MHz (OC)',
    pcie_slots: '1 x PCIe 5.0 x16, 1 x PCIe 4.0 x16',
    storage_support: '4 x M.2, 6 x SATA 6Gb/s',
    network: 'WiFi 6E + 2.5G LAN',
    usb_ports: 'USB 3.2 Gen 2x2, Type-C',
    audio: 'AMP-UP Audio',
    price: 28999,
    warranty: '3 Years',
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Motherboards/Gigabyte%20Z790%20AORUS%20ELITE%20AX.jpg?updatedAt=1761832377921',
  },
  {
    id: 'mb004',
    name: 'ASRock B550M Steel Legend',
    brand: 'ASRock',
    category: 'Motherboard',
    socket: 'AM4',
    chipset: 'AMD B550',
    form_factor: 'Micro-ATX',
    supported_cpu: 'AMD Ryzen 3000 / 5000 Series',
    supported_ram: 'DDR4 up to 128GB',
    ram_slots: 4,
    max_ram_speed: '4733 MHz (OC)',
    pcie_slots: '1 x PCIe 4.0 x16, 1 x PCIe 3.0 x16',
    storage_support: '2 x M.2, 4 x SATA 6Gb/s',
    network: '2.5G LAN',
    usb_ports: 'USB 3.2 Gen 2, Type-C',
    audio: '7.1 CH HD Audio',
    price: 13999,
    warranty: '3 Years',
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Motherboards/ASRock%20B550M%20Steel%20Legend.jpg?updatedAt=1761832376102',
  },
  {
    id: 'mb005',
    name: 'MSI PRO Z690-A DDR5',
    brand: 'MSI',
    category: 'Motherboard',
    socket: 'LGA 1700',
    chipset: 'Intel Z690',
    form_factor: 'ATX',
    supported_cpu: 'Intel 12th / 13th Gen',
    supported_ram: 'DDR5 up to 128GB',
    ram_slots: 4,
    max_ram_speed: '6400 MHz (OC)',
    pcie_slots: '1 x PCIe 5.0 x16, 2 x PCIe 3.0 x16',
    storage_support: '4 x M.2, 6 x SATA 6Gb/s',
    network: '2.5G LAN',
    usb_ports: 'USB 3.2 Gen 2x2, Type-C',
    audio: 'Realtek ALC897 Audio',
    price: 22999,
    warranty: '3 Years',
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Motherboards/MSI%20PRO%20Z690-A%20DDR5.jpg?updatedAt=1761832377689',
  },
  {
    id: 'mb006',
    name: 'Gigabyte B660M DS3H AX DDR4',
    brand: 'Gigabyte',
    category: 'Motherboard',
    socket: 'LGA 1700',
    chipset: 'Intel B660',
    form_factor: 'Micro-ATX',
    supported_cpu: 'Intel 12th / 13th Gen',
    supported_ram: 'DDR4 up to 128GB',
    ram_slots: 4,
    max_ram_speed: '5333 MHz (OC)',
    pcie_slots: '1 x PCIe 4.0 x16, 2 x PCIe 3.0 x1',
    storage_support: '2 x M.2, 4 x SATA 6Gb/s',
    network: 'WiFi 6 + 2.5G LAN',
    usb_ports: 'USB 3.2 Gen 2, Type-C',
    audio: 'Realtek 8-Channel HD Audio',
    price: 14999,
    warranty: '3 Years',
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Motherboards/Gigabyte%20B660M%20DS3H%20AX%20DDR4.jpg?updatedAt=1761832378111',
  },
  {
    id: 'mb007',
    name: 'ASUS PRIME X670-P WIFI',
    brand: 'ASUS',
    category: 'Motherboard',
    socket: 'AM5',
    chipset: 'AMD X670',
    form_factor: 'ATX',
    supported_cpu: 'AMD Ryzen 7000 Series',
    supported_ram: 'DDR5 up to 128GB',
    ram_slots: 4,
    max_ram_speed: '6400 MHz (OC)',
    pcie_slots: '1 x PCIe 5.0 x16, 2 x PCIe 4.0 x16',
    storage_support: '3 x M.2, 4 x SATA 6Gb/s',
    network: 'WiFi 6 + 2.5G LAN',
    usb_ports: 'USB 3.2 Gen 2x2, Type-C',
    audio: 'Realtek 7.1 Surround',
    price: 31999,
    warranty: '3 Years',
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Motherboards/ASUS%20PRIME%20X670-P%20WIFI.jpg?updatedAt=1761832377823',
  },
  {
    id: 'mb008',
    name: 'ASRock X670E Taichi',
    brand: 'ASRock',
    category: 'Motherboard',
    socket: 'AM5',
    chipset: 'AMD X670E',
    form_factor: 'ATX',
    supported_cpu: 'AMD Ryzen 7000 Series',
    supported_ram: 'DDR5 up to 128GB',
    ram_slots: 4,
    max_ram_speed: '6600 MHz (OC)',
    pcie_slots: '1 x PCIe 5.0 x16, 1 x PCIe 4.0 x16',
    storage_support: '4 x M.2, 8 x SATA 6Gb/s',
    network: 'WiFi 6E + 2.5G LAN',
    usb_ports: 'USB 4.0 Type-C, USB 3.2 Gen 2x2',
    audio: 'ESS SABRE9218 DAC',
    price: 44999,
    warranty: '3 Years',
    availability: 'Limited Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Motherboards/ASRock%20X670E%20Taichi.jpg?updatedAt=1761832377897',
  },
  {
    id: 'mb009',
    name: 'Gigabyte TRX40 AORUS XTREME',
    brand: 'Gigabyte',
    category: 'Motherboard',
    socket: 'sTRX4',
    chipset: 'AMD TRX40',
    form_factor: 'E-ATX',
    supported_cpu: 'AMD Ryzen Threadripper',
    supported_ram: 'DDR4 up to 256GB',
    ram_slots: 8,
    max_ram_speed: '4400 MHz (OC)',
    pcie_slots: '4 x PCIe 4.0 x16',
    storage_support: '4 x M.2, 8 x SATA 6Gb/s',
    network: '10G LAN + WiFi 6',
    usb_ports: 'USB 3.2 Gen 2x2, Type-C',
    audio: 'ESS SABRE DAC',
    price: 89999,
    warranty: '3 Years',
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Motherboards/Gigabyte%20TRX40%20AORUS%20XTREME.jpg?updatedAt=1761832378136',
  },
  {
    id: 'mb010',
    name: 'Supermicro X13SAE Workstation Motherboard',
    brand: 'Supermicro',
    category: 'Motherboard',
    socket: 'LGA 1700',
    chipset: 'Intel W680',
    form_factor: 'ATX',
    supported_cpu: 'Intel Xeon W / 12th Gen Core',
    supported_ram: 'DDR5 ECC up to 128GB',
    ram_slots: 4,
    max_ram_speed: '5600 MHz',
    pcie_slots: '1 x PCIe 5.0 x16, 2 x PCIe 4.0 x16',
    storage_support: '3 x M.2, 6 x SATA 6Gb/s',
    network: 'Dual 2.5G LAN',
    usb_ports: 'USB 3.2 Gen 2, Type-C',
    audio: '7.1 HD Audio',
    price: 58999,
    warranty: '3 Years',
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Motherboards/Supermicro%20X13SAE%20Workstation%20Motherboard.jpg?updatedAt=1761832377105',
  },
];

const RAM = [
  {
    id: 'ram001',
    name: 'Corsair Vengeance DDR5 32GB (2x16GB) 6000MHz',
    brand: 'Corsair',
    category: 'RAM Module',
    type: 'DDR5',
    capacity: '32GB (2x16GB)',
    speed: '6000 MHz',
    latency: 'CL36',
    voltage: '1.35V',
    form_factor: 'DIMM',
    compatibility: 'Intel 12th/13th Gen, AMD AM5',
    rgb: 'Yes',
    warranty: 'Lifetime',
    price: 13999,
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/RAM/Corsair%20Vengeance%20DDR5%2032GB%20(2x16GB)%206000MHz.webp?updatedAt=1761832463482',
  },
  {
    id: 'ram002',
    name: 'G.Skill Trident Z5 RGB DDR5 64GB (2x32GB) 6400MHz',
    brand: 'G.Skill',
    category: 'RAM Module',
    type: 'DDR5',
    capacity: '64GB (2x32GB)',
    speed: '6400 MHz',
    latency: 'CL32',
    voltage: '1.4V',
    form_factor: 'DIMM',
    compatibility: 'Intel Z790 / AMD X670E',
    rgb: 'Yes',
    warranty: 'Lifetime',
    price: 25999,
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/RAM/G.Skill%20Trident%20Z5%20RGB%20DDR5%2064GB%20(2x32GB)%206400MHz.jpg?updatedAt=1761832463697',
  },
  {
    id: 'ram003',
    name: 'Kingston Fury Beast DDR4 16GB (1x16GB) 3200MHz',
    brand: 'Kingston',
    category: 'RAM Module',
    type: 'DDR4',
    capacity: '16GB',
    speed: '3200 MHz',
    latency: 'CL16',
    voltage: '1.35V',
    form_factor: 'DIMM',
    compatibility: 'Intel / AMD',
    rgb: 'No',
    warranty: 'Lifetime',
    price: 3999,
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/RAM/Kingston%20Fury%20Beast%20DDR4%2016GB%20(1x16GB)%203200MHz.jpeg?updatedAt=1761832463800',
  },
  {
    id: 'ram004',
    name: 'Crucial Pro DDR5 32GB (2x16GB) 5600MHz',
    brand: 'Crucial',
    category: 'RAM Module',
    type: 'DDR5',
    capacity: '32GB (2x16GB)',
    speed: '5600 MHz',
    latency: 'CL46',
    voltage: '1.1V',
    form_factor: 'DIMM',
    compatibility: 'Intel 12th/13th Gen, AMD AM5',
    rgb: 'No',
    warranty: 'Lifetime',
    price: 11499,
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/RAM/Crucial%20Pro%20DDR5%2032GB%20(2x16GB)%205600MHz.png?updatedAt=1761832463470',
  },
  {
    id: 'ram005',
    name: 'TeamGroup T-Force Delta RGB DDR4 32GB (2x16GB) 3600MHz',
    brand: 'TeamGroup',
    category: 'RAM Module',
    type: 'DDR4',
    capacity: '32GB (2x16GB)',
    speed: '3600 MHz',
    latency: 'CL18',
    voltage: '1.35V',
    form_factor: 'DIMM',
    compatibility: 'Intel / AMD',
    rgb: 'Yes',
    warranty: 'Lifetime',
    price: 8799,
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/RAM/TeamGroup%20T-Force%20Delta%20RGB%20DDR4%2032GB%20(2x16GB)%203600MHz.jpg?updatedAt=1761832463728',
  },
  {
    id: 'ram006',
    name: 'ADATA XPG Lancer DDR5 32GB (2x16GB) 6000MHz',
    brand: 'ADATA',
    category: 'RAM Module',
    type: 'DDR5',
    capacity: '32GB (2x16GB)',
    speed: '6000 MHz',
    latency: 'CL40',
    voltage: '1.35V',
    form_factor: 'DIMM',
    compatibility: 'Intel Z690 / AMD X670',
    rgb: 'Yes',
    warranty: 'Lifetime',
    price: 12999,
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/RAM/ADATA%20XPG%20Lancer%20DDR5%2032GB%20(2x16GB)%206000MHz.jpeg?updatedAt=1761832463429',
  },
  {
    id: 'ram007',
    name: 'Patriot Viper Steel DDR4 16GB (2x8GB) 4000MHz',
    brand: 'Patriot',
    category: 'RAM Module',
    type: 'DDR4',
    capacity: '16GB (2x8GB)',
    speed: '4000 MHz',
    latency: 'CL19',
    voltage: '1.35V',
    form_factor: 'DIMM',
    compatibility: 'Intel / AMD',
    rgb: 'No',
    warranty: 'Lifetime',
    price: 6999,
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/RAM/Patriot%20Viper%20Steel%20DDR4%2016GB%20(2x8GB)%204000MHz.jpg?updatedAt=1761832463656',
  },
  {
    id: 'ram008',
    name: 'G.Skill Ripjaws S5 DDR5 32GB (2x16GB) 5600MHz',
    brand: 'G.Skill',
    category: 'RAM Module',
    type: 'DDR5',
    capacity: '32GB (2x16GB)',
    speed: '5600 MHz',
    latency: 'CL36',
    voltage: '1.25V',
    form_factor: 'DIMM',
    compatibility: 'Intel 12th/13th Gen',
    rgb: 'No',
    warranty: 'Lifetime',
    price: 12499,
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/RAM/G.Skill%20Ripjaws%20S5%20DDR5%2032GB%20(2x16GB)%205600MHz.jpeg?updatedAt=1761832463755',
  },
  {
    id: 'ram009',
    name: 'Corsair Vengeance LPX DDR4 8GB (1x8GB) 3000MHz',
    brand: 'Corsair',
    category: 'RAM Module',
    type: 'DDR4',
    capacity: '8GB',
    speed: '3000 MHz',
    latency: 'CL15',
    voltage: '1.35V',
    form_factor: 'DIMM',
    compatibility: 'Intel / AMD',
    rgb: 'No',
    warranty: 'Lifetime',
    price: 2499,
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/RAM/Corsair%20Vengeance%20LPX%20DDR4%208GB%20(1x8GB)%203000MHz.jpg?updatedAt=1761832463579',
  },
  {
    id: 'ram010',
    name: 'Samsung DDR5 48GB (1x48GB) 5600MHz OEM',
    brand: 'Samsung',
    category: 'RAM Module',
    type: 'DDR5',
    capacity: '48GB',
    speed: '5600 MHz',
    latency: 'CL46',
    voltage: '1.1V',
    form_factor: 'DIMM',
    compatibility: 'Intel / AMD',
    rgb: 'No',
    warranty: '3 Years',
    price: 10999,
    availability: 'In Stock',
    imageUrls:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/RAM/Samsung%20DDR5%2048GB%20(1x48GB)%205600MHz%20OEM.webp?updatedAt=1761832463832',
  },
];

const storageDevices = [
  {
    id: 1,
    name: 'Samsung 970 EVO Plus NVMe M.2 SSD 1TB',
    brand: 'Samsung',
    type: 'SSD (NVMe)',
    capacity: '1TB',
    interface: 'PCIe Gen 3.0 x4 NVMe 1.3',
    readSpeed: '3500 MB/s',
    writeSpeed: '3300 MB/s',
    warranty: '5 Years',
    price: 9499,
    compatibility: 'Laptop & Desktop',
    description:
      'High-performance NVMe SSD ideal for gaming, content creation, and heavy workloads with exceptional reliability.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Storage%20device/Samsung%20970%20EVO%20Plus%20NVMe%20M.2%20SSD%201TB.jpg?updatedAt=1761832484936',
  },
  {
    id: 2,
    name: 'WD Blue SN570 NVMe SSD 500GB',
    brand: 'Western Digital',
    type: 'SSD (NVMe)',
    capacity: '500GB',
    interface: 'PCIe Gen 3.0 x4',
    readSpeed: '3500 MB/s',
    writeSpeed: '2300 MB/s',
    warranty: '5 Years',
    price: 4199,
    compatibility: 'Laptop & Desktop',
    description:
      'Reliable NVMe storage solution designed for faster system responsiveness and smooth multitasking.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Storage%20device/WD%20Blue%20SN570%20NVMe%20SSD%20500GB.jpg?updatedAt=1761832485214',
  },
  {
    id: 3,
    name: 'Crucial MX500 SATA SSD 1TB',
    brand: 'Crucial',
    type: 'SSD (SATA)',
    capacity: '1TB',
    interface: 'SATA III 6Gb/s',
    readSpeed: '560 MB/s',
    writeSpeed: '510 MB/s',
    warranty: '5 Years',
    price: 6499,
    compatibility: 'Laptop & Desktop',
    description:
      'SATA SSD delivering excellent performance, durability, and energy efficiency for everyday computing.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Storage%20device/Crucial%20MX500%20SATA%20SSD%201TB.jpg?updatedAt=1761832485164',
  },
  {
    id: 4,
    name: 'Seagate Barracuda HDD 2TB 7200RPM',
    brand: 'Seagate',
    type: 'HDD',
    capacity: '2TB',
    interface: 'SATA III 6Gb/s',
    rpm: '7200 RPM',
    cache: '256MB',
    warranty: '2 Years',
    price: 4999,
    compatibility: 'Desktop',
    description:
      'High-capacity HDD designed for everyday desktop computing and large file storage.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Storage%20device/Seagate%20Barracuda%20HDD%202TB%207200RPM.jpg?updatedAt=1761832485021',
  },
  {
    id: 5,
    name: 'Toshiba P300 Performance HDD 1TB',
    brand: 'Toshiba',
    type: 'HDD',
    capacity: '1TB',
    interface: 'SATA III 6Gb/s',
    rpm: '7200 RPM',
    cache: '64MB',
    warranty: '3 Years',
    price: 3599,
    compatibility: 'Desktop',
    description:
      'Reliable HDD built for performance and durability, ideal for gaming and multimedia systems.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Storage%20device/Toshiba%20P300%20Performance%20HDD%201TB.jpg?updatedAt=1761832485006',
  },
  {
    id: 6,
    name: 'Kingston A400 SATA SSD 480GB',
    brand: 'Kingston',
    type: 'SSD (SATA)',
    capacity: '480GB',
    interface: 'SATA III 6Gb/s',
    readSpeed: '500 MB/s',
    writeSpeed: '450 MB/s',
    warranty: '3 Years',
    price: 2799,
    compatibility: 'Laptop & Desktop',
    description:
      'Affordable SSD that dramatically improves system responsiveness and boot times compared to HDDs.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Storage%20device/Kingston%20A400%20SATA%20SSD%20480GB.jpg?updatedAt=1761832485138',
  },
  {
    id: 7,
    name: 'ADATA XPG SX8200 Pro NVMe M.2 SSD 1TB',
    brand: 'ADATA',
    type: 'SSD (NVMe)',
    capacity: '1TB',
    interface: 'PCIe Gen 3.0 x4',
    readSpeed: '3500 MB/s',
    writeSpeed: '3000 MB/s',
    warranty: '5 Years',
    price: 8999,
    compatibility: 'Laptop & Desktop',
    description:
      'Premium NVMe SSD offering outstanding performance and endurance for gaming and content creation.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Storage%20device/ADATA%20XPG%20SX8200%20Pro%20NVMe%20M.2%20SSD%201TB.jpg?updatedAt=1761832485202',
  },
  {
    id: 8,
    name: 'WD Black SN850X NVMe SSD 2TB',
    brand: 'Western Digital',
    type: 'SSD (NVMe)',
    capacity: '2TB',
    interface: 'PCIe Gen 4.0 x4',
    readSpeed: '7300 MB/s',
    writeSpeed: '6600 MB/s',
    warranty: '5 Years',
    price: 17499,
    compatibility: 'Laptop & Desktop',
    description:
      'Top-tier PCIe Gen4 SSD built for gaming, with blazing-fast speeds and superior thermal control.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Storage%20device/WD%20Black%20SN850X%20NVMe%20SSD%202TB.jpg?updatedAt=1761832485124',
  },
  {
    id: 9,
    name: 'Seagate FireCuda Gaming SSHD 2TB',
    brand: 'Seagate',
    type: 'SSHD (Hybrid)',
    capacity: '2TB',
    interface: 'SATA III 6Gb/s',
    rpm: '7200 RPM',
    cache: '8GB NAND Flash',
    warranty: '5 Years',
    price: 6999,
    compatibility: 'Desktop & Console',
    description:
      'Hybrid drive combining SSD-like speed with HDD capacity, ideal for gaming systems.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Storage%20device/Seagate%20FireCuda%20Gaming%20SSHD%202TB.jpg?updatedAt=1761832485170',
  },
  {
    id: 10,
    name: 'Samsung 870 QVO SATA SSD 2TB',
    brand: 'Samsung',
    type: 'SSD (SATA)',
    capacity: '2TB',
    interface: 'SATA III 6Gb/s',
    readSpeed: '560 MB/s',
    writeSpeed: '530 MB/s',
    warranty: '3 Years',
    price: 10499,
    compatibility: 'Laptop & Desktop',
    description:
      'High-capacity QLC SSD providing reliable performance and efficient data storage for professionals.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Storage%20device/Samsung%20870%20QVO%20SATA%20SSD%202TB.webp?updatedAt=1761832485273',
  },
];

const graphicsCards = [
  {
    id: 1,
    name: 'NVIDIA GeForce RTX 4090 Founders Edition',
    brand: 'NVIDIA',
    chipset: 'GeForce RTX 4090',
    vram: '24GB GDDR6X',
    memoryBus: '384-bit',
    baseClock: '2230 MHz',
    boostClock: '2520 MHz',
    tdp: '450W',
    powerConnector: '16-pin',
    recommendedPSU: '850W',
    ports: ['HDMI 2.1', 'DisplayPort 1.4a x3'],
    price: 184999,
    warranty: '3 Years',
    compatibility: 'Desktop',
    description:
      'Flagship GPU designed for 4K gaming, 3D rendering, and AI workloads with Ada Lovelace architecture.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/graphicsCards/NVIDIA%20GeForce%20RTX%204090%20Founders%20Edition.jpg?updatedAt=1761832349342',
  },
  {
    id: 2,
    name: 'AMD Radeon RX 7900 XTX',
    brand: 'AMD',
    chipset: 'Radeon RX 7900 XTX',
    vram: '24GB GDDR6',
    memoryBus: '384-bit',
    baseClock: '1855 MHz',
    boostClock: '2499 MHz',
    tdp: '355W',
    powerConnector: '8-pin x2',
    recommendedPSU: '750W',
    ports: ['HDMI 2.1', 'DisplayPort 2.1 x2', 'USB-C'],
    price: 139999,
    warranty: '3 Years',
    compatibility: 'Desktop',
    description:
      'High-end GPU offering outstanding 4K gaming and ray tracing with RDNA 3 architecture.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/graphicsCards/AMD%20Radeon%20RX%207900%20XTX.jpg?updatedAt=1761832348648',
  },
  {
    id: 3,
    name: 'NVIDIA GeForce RTX 4070 Ti SUPER',
    brand: 'NVIDIA',
    chipset: 'GeForce RTX 4070 Ti SUPER',
    vram: '16GB GDDR6X',
    memoryBus: '256-bit',
    baseClock: '2310 MHz',
    boostClock: '2610 MHz',
    tdp: '285W',
    powerConnector: '16-pin',
    recommendedPSU: '700W',
    ports: ['HDMI 2.1', 'DisplayPort 1.4a x3'],
    price: 85999,
    warranty: '3 Years',
    compatibility: 'Desktop',
    description:
      'Powerful GPU for 1440p and 4K gaming with excellent ray tracing and AI DLSS 3 support.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/graphicsCards/NVIDIA%20GeForce%20RTX%204070%20Ti%20SUPER.jpg?updatedAt=1761832349391',
  },
  {
    id: 4,
    name: 'AMD Radeon RX 7800 XT',
    brand: 'AMD',
    chipset: 'Radeon RX 7800 XT',
    vram: '16GB GDDR6',
    memoryBus: '256-bit',
    baseClock: '2124 MHz',
    boostClock: '2430 MHz',
    tdp: '263W',
    powerConnector: '8-pin x2',
    recommendedPSU: '700W',
    ports: ['HDMI 2.1', 'DisplayPort 2.1 x3'],
    price: 61999,
    warranty: '3 Years',
    compatibility: 'Desktop',
    description:
      'Mid-high range GPU for smooth 1440p gaming with RDNA 3 efficiency and low noise cooling.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/graphicsCards/AMD%20Radeon%20RX%207800%20XT.jpg?updatedAt=1761832348502',
  },
  {
    id: 5,
    name: 'NVIDIA GeForce RTX 4060 Ti',
    brand: 'NVIDIA',
    chipset: 'GeForce RTX 4060 Ti',
    vram: '8GB GDDR6',
    memoryBus: '128-bit',
    baseClock: '2310 MHz',
    boostClock: '2535 MHz',
    tdp: '160W',
    powerConnector: '8-pin',
    recommendedPSU: '550W',
    ports: ['HDMI 2.1', 'DisplayPort 1.4a x3'],
    price: 43999,
    warranty: '3 Years',
    compatibility: 'Desktop',
    description:
      'Efficient GPU for 1080p and 1440p gaming, perfect balance between performance and power usage.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/graphicsCards/NVIDIA%20GeForce%20RTX%204060%20Ti.jpg?updatedAt=1761832349346',
  },
  {
    id: 6,
    name: 'ZOTAC Gaming GeForce RTX 3060 Twin Edge',
    brand: 'ZOTAC',
    chipset: 'GeForce RTX 3060',
    vram: '12GB GDDR6',
    memoryBus: '192-bit',
    baseClock: '1320 MHz',
    boostClock: '1777 MHz',
    tdp: '170W',
    powerConnector: '8-pin',
    recommendedPSU: '550W',
    ports: ['HDMI 2.1', 'DisplayPort 1.4a x3'],
    price: 29999,
    warranty: '2 Years',
    compatibility: 'Desktop',
    description:
      'Affordable RTX GPU delivering solid 1080p performance and ray tracing support for mid-range PCs.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/graphicsCards/ZOTAC%20Gaming%20GeForce%20RTX%203060%20Twin%20Edge.jpg?updatedAt=1761832349385',
  },
  {
    id: 7,
    name: 'ASUS TUF Gaming Radeon RX 6700 XT',
    brand: 'ASUS',
    chipset: 'Radeon RX 6700 XT',
    vram: '12GB GDDR6',
    memoryBus: '192-bit',
    baseClock: '2321 MHz',
    boostClock: '2581 MHz',
    tdp: '230W',
    powerConnector: '8-pin x2',
    recommendedPSU: '650W',
    ports: ['HDMI 2.1', 'DisplayPort 1.4 x3'],
    price: 47999,
    warranty: '3 Years',
    compatibility: 'Desktop',
    description:
      'Gaming-grade GPU offering strong 1440p performance with durable cooling and design.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/graphicsCards/ASUS%20TUF%20Gaming%20Radeon%20RX%206700%20XT.jpg?updatedAt=1761832349424',
  },
  {
    id: 8,
    name: 'Gigabyte GeForce GTX 1660 Super OC',
    brand: 'Gigabyte',
    chipset: 'GeForce GTX 1660 Super',
    vram: '6GB GDDR6',
    memoryBus: '192-bit',
    baseClock: '1530 MHz',
    boostClock: '1830 MHz',
    tdp: '125W',
    powerConnector: '8-pin',
    recommendedPSU: '450W',
    ports: ['HDMI 2.0b', 'DisplayPort 1.4 x3'],
    price: 19999,
    warranty: '3 Years',
    compatibility: 'Desktop',
    description:
      'Budget-friendly GPU with excellent 1080p gaming performance and low power consumption.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/graphicsCards/Gigabyte%20GeForce%20GTX%201660%20Super%20OC.jpeg?updatedAt=1761832349391',
  },
  {
    id: 9,
    name: 'MSI GeForce RTX 4070 Gaming X Trio',
    brand: 'MSI',
    chipset: 'GeForce RTX 4070',
    vram: '12GB GDDR6X',
    memoryBus: '192-bit',
    baseClock: '1920 MHz',
    boostClock: '2610 MHz',
    tdp: '200W',
    powerConnector: '16-pin',
    recommendedPSU: '650W',
    ports: ['HDMI 2.1', 'DisplayPort 1.4a x3'],
    price: 64999,
    warranty: '3 Years',
    compatibility: 'Desktop',
    description:
      'Quiet and efficient GPU for 1440p and light 4K gaming, featuring advanced cooling and DLSS 3 support.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/graphicsCards/MSI%20GeForce%20RTX%204070%20Gaming%20X%20Trio.jpg?updatedAt=1761832349306',
  },
  {
    id: 10,
    name: 'Sapphire Nitro+ Radeon RX 6600 XT',
    brand: 'Sapphire',
    chipset: 'Radeon RX 6600 XT',
    vram: '8GB GDDR6',
    memoryBus: '128-bit',
    baseClock: '1968 MHz',
    boostClock: '2589 MHz',
    tdp: '160W',
    powerConnector: '8-pin',
    recommendedPSU: '550W',
    ports: ['HDMI 2.1', 'DisplayPort 1.4 x3'],
    price: 32999,
    warranty: '3 Years',
    compatibility: 'Desktop',
    description:
      'Solid 1080p and 1440p GPU with excellent efficiency and minimal heat output using RDNA 2 tech.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/graphicsCards/Sapphire%20Nitro+%20Radeon%20RX%206600%20XT.jpg?updatedAt=1761832349295',
  },
];

const powerSupplies = [
  {
    id: 1,
    name: 'Corsair RM850x Fully Modular PSU',
    brand: 'Corsair',
    wattage: '850W',
    efficiency: '80+ Gold',
    modularity: 'Fully Modular',
    fanSize: '135mm',
    inputVoltage: '100-240V',
    formFactor: 'ATX',
    warranty: '10 Years',
    price: 12499,
    compatibility: 'Desktop',
    description:
      'High-performance PSU with 80+ Gold efficiency and low-noise operation, perfect for high-end gaming PCs.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Power%20supplier/Corsair%20RM850x%20Fully%20Modular%20PSU.jpg?updatedAt=1761832404052',
  },
  {
    id: 2,
    name: 'Cooler Master MWE Bronze 650W V2',
    brand: 'Cooler Master',
    wattage: '650W',
    efficiency: '80+ Bronze',
    modularity: 'Non-Modular',
    fanSize: '120mm',
    inputVoltage: '100-240V',
    formFactor: 'ATX',
    warranty: '5 Years',
    price: 5499,
    compatibility: 'Desktop',
    description:
      'Reliable and affordable PSU with silent cooling, ideal for mid-range gaming systems.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Power%20supplier/Cooler%20Master%20MWE%20Bronze%20650W%20V2.jpg?updatedAt=1761832404187',
  },
  {
    id: 3,
    name: 'Antec HCG 750 Gold High Current Gamer',
    brand: 'Antec',
    wattage: '750W',
    efficiency: '80+ Gold',
    modularity: 'Semi-Modular',
    fanSize: '135mm FDB Fan',
    inputVoltage: '100-240V',
    formFactor: 'ATX',
    warranty: '7 Years',
    price: 8999,
    compatibility: 'Desktop',
    description:
      'High-efficiency PSU built for gamers with premium Japanese capacitors and quiet operation.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Power%20supplier/Antec%20HCG%20750%20Gold%20High%20Current%20Gamer.jpg?updatedAt=1761832403534',
  },
  {
    id: 4,
    name: 'Seasonic Focus GX-650 Fully Modular PSU',
    brand: 'Seasonic',
    wattage: '650W',
    efficiency: '80+ Gold',
    modularity: 'Fully Modular',
    fanSize: '120mm Fluid Dynamic Bearing',
    inputVoltage: '100-240V',
    formFactor: 'ATX',
    warranty: '10 Years',
    price: 8899,
    compatibility: 'Desktop',
    description:
      'Compact and efficient PSU offering stable power delivery and long-lasting durability.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Power%20supplier/Seasonic%20Focus%20GX-650%20Fully%20Modular%20PSU.jpg?updatedAt=1761832404095',
  },
  {
    id: 5,
    name: 'MSI MPG A850G PCIE5 Fully Modular',
    brand: 'MSI',
    wattage: '850W',
    efficiency: '80+ Gold',
    modularity: 'Fully Modular',
    fanSize: '140mm',
    inputVoltage: '100-240V',
    formFactor: 'ATX',
    warranty: '10 Years',
    price: 10999,
    compatibility: 'Desktop',
    description:
      'Next-gen PSU supporting PCIe 5.0 and ATX 3.0 standards, ideal for RTX 40-series builds.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Power%20supplier/MSI%20MPG%20A850G%20PCIE5%20Fully%20Modular.jpg?updatedAt=1761832404116',
  },
  {
    id: 6,
    name: 'EVGA SuperNOVA 1000 G5',
    brand: 'EVGA',
    wattage: '1000W',
    efficiency: '80+ Gold',
    modularity: 'Fully Modular',
    fanSize: '135mm Fluid Dynamic Bearing',
    inputVoltage: '100-240V',
    formFactor: 'ATX',
    warranty: '10 Years',
    price: 14999,
    compatibility: 'Desktop',
    description:
      'Heavy-duty PSU with excellent power stability for overclocked and multi-GPU systems.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Power%20supplier/EVGA%20SuperNOVA%201000%20G5.jpg?updatedAt=1761832404123',
  },
  {
    id: 7,
    name: 'Thermaltake Smart RGB 700W',
    brand: 'Thermaltake',
    wattage: '700W',
    efficiency: '80+ White',
    modularity: 'Non-Modular',
    fanSize: '120mm RGB Fan',
    inputVoltage: '100-240V',
    formFactor: 'ATX',
    warranty: '5 Years',
    price: 4799,
    compatibility: 'Desktop',
    description:
      'Stylish PSU with RGB lighting and reliable power for budget gaming and office builds.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Power%20supplier/Thermaltake%20Smart%20RGB%20700W.jpg?updatedAt=1761832404158',
  },
  {
    id: 8,
    name: 'Gigabyte P850GM Fully Modular PSU',
    brand: 'Gigabyte',
    wattage: '850W',
    efficiency: '80+ Gold',
    modularity: 'Fully Modular',
    fanSize: '120mm Hydraulic Bearing Fan',
    inputVoltage: '100-240V',
    formFactor: 'ATX',
    warranty: '10 Years',
    price: 9599,
    compatibility: 'Desktop',
    description:
      'Compact, gold-rated PSU with stable voltage and superior thermal efficiency for gaming builds.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Power%20supplier/Gigabyte%20P850GM%20Fully%20Modular%20PSU.jpg?updatedAt=1761832404183',
  },
  {
    id: 9,
    name: 'Corsair CV550 Power Supply',
    brand: 'Corsair',
    wattage: '550W',
    efficiency: '80+ Bronze',
    modularity: 'Non-Modular',
    fanSize: '120mm',
    inputVoltage: '100-240V',
    formFactor: 'ATX',
    warranty: '3 Years',
    price: 3799,
    compatibility: 'Desktop',
    description:
      'Budget-friendly PSU offering consistent power output and quiet operation for entry-level systems.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Power%20supplier/Corsair%20CV550%20Power%20Supply.jpg?updatedAt=1761832404024',
  },
  {
    id: 10,
    name: 'Be Quiet! Straight Power 11 750W',
    brand: 'Be Quiet!',
    wattage: '750W',
    efficiency: '80+ Platinum',
    modularity: 'Fully Modular',
    fanSize: '135mm Silent Wings 3',
    inputVoltage: '100-240V',
    formFactor: 'ATX',
    warranty: '10 Years',
    price: 13299,
    compatibility: 'Desktop',
    description:
      'Ultra-quiet, high-efficiency PSU with exceptional voltage regulation and premium German engineering.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/Power%20supplier/Be%20Quiet!%20Straight%20Power%2011%20750W.jpg?updatedAt=1761832403622',
  },
];

const coolingSystems = [
  {
    id: 1,
    name: 'Cooler Master Hyper 212 Black Edition',
    brand: 'Cooler Master',
    type: 'Air Cooler',
    fanSize: '120mm',
    heatPipes: 4,
    rpmRange: '600 - 2000 RPM',
    noiseLevel: '26 dBA',
    socketSupport: ['LGA1700', 'LGA1200', 'AM5', 'AM4'],
    dimensions: '123 x 77 x 158.8 mm',
    warranty: '2 Years',
    price: 3499,
    compatibility: 'Desktop',
    description:
      'Legendary air cooler with a sleek black design and excellent thermal performance for mainstream CPUs.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/coolingSystems/Cooler%20Master%20Hyper%20212%20Black%20Edition.jpg?updatedAt=1761832322995',
  },
  {
    id: 2,
    name: 'Corsair iCUE H100i Elite Capellix Liquid Cooler',
    brand: 'Corsair',
    type: 'Liquid Cooler (AIO)',
    radiatorSize: '240mm',
    fanSize: '120mm x2',
    rpmRange: '400 - 2400 RPM',
    noiseLevel: '36 dBA',
    socketSupport: ['LGA1700', 'LGA1200', 'AM5', 'AM4'],
    dimensions: '277 x 120 x 27 mm',
    warranty: '5 Years',
    price: 12999,
    compatibility: 'Desktop',
    description:
      'High-performance RGB AIO cooler with advanced iCUE software control for temperature and lighting.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/coolingSystems/Corsair%20iCUE%20H100i%20Elite%20Capellix%20Liquid%20Cooler.jpg?updatedAt=1761832323030',
  },
  {
    id: 3,
    name: 'NZXT Kraken X63 RGB',
    brand: 'NZXT',
    type: 'Liquid Cooler (AIO)',
    radiatorSize: '280mm',
    fanSize: '140mm x2',
    rpmRange: '500 - 1800 RPM',
    noiseLevel: '36 dBA',
    socketSupport: ['LGA1700', 'LGA1200', 'AM5', 'AM4'],
    dimensions: '315 x 143 x 30 mm',
    warranty: '6 Years',
    price: 14999,
    compatibility: 'Desktop',
    description:
      'Stylish liquid cooler featuring infinity mirror design and customizable RGB lighting for premium builds.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/coolingSystems/NZXT%20Kraken%20X63%20RGB.jpg?updatedAt=1761832323006',
  },
  {
    id: 4,
    name: 'DeepCool AK620 High-Performance Air Cooler',
    brand: 'DeepCool',
    type: 'Air Cooler',
    fanSize: '120mm x2',
    heatPipes: 6,
    rpmRange: '500 - 1850 RPM',
    noiseLevel: '28 dBA',
    socketSupport: ['LGA1700', 'AM5', 'AM4'],
    dimensions: '129 x 138 x 160 mm',
    warranty: '3 Years',
    price: 5999,
    compatibility: 'Desktop',
    description:
      'Dual-tower air cooler offering excellent thermal control and quiet operation for high-end CPUs.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/coolingSystems/DeepCool%20AK620%20High-Performance%20Air%20Cooler.jpg?updatedAt=1761832323093',
  },
  {
    id: 5,
    name: 'Noctua NH-D15 Chromax.Black',
    brand: 'Noctua',
    type: 'Air Cooler',
    fanSize: '140mm x2',
    heatPipes: 6,
    rpmRange: '300 - 1500 RPM',
    noiseLevel: '24.6 dBA',
    socketSupport: ['LGA1700', 'AM5', 'AM4'],
    dimensions: '150 x 161 x 165 mm',
    warranty: '6 Years',
    price: 10999,
    compatibility: 'Desktop',
    description:
      'Premium dual-tower cooler with unmatched cooling performance and ultra-quiet operation.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/coolingSystems/Noctua%20NH-D15%20Chromax.Black.jpg?updatedAt=1761832323031',
  },
  {
    id: 6,
    name: 'Arctic Liquid Freezer II 280',
    brand: 'Arctic',
    type: 'Liquid Cooler (AIO)',
    radiatorSize: '280mm',
    fanSize: '140mm x2',
    rpmRange: '200 - 1700 RPM',
    noiseLevel: '35.8 dBA',
    socketSupport: ['LGA1700', 'LGA1200', 'AM5', 'AM4'],
    dimensions: '317 x 138 x 38 mm',
    warranty: '6 Years',
    price: 9999,
    compatibility: 'Desktop',
    description:
      'Efficient AIO cooler with integrated VRM fan for better overall system cooling and low noise levels.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/coolingSystems/Arctic%20Liquid%20Freezer%20II%20280.jpg?updatedAt=1761832322876',
  },
  {
    id: 7,
    name: 'Cooler Master MasterLiquid ML360R RGB',
    brand: 'Cooler Master',
    type: 'Liquid Cooler (AIO)',
    radiatorSize: '360mm',
    fanSize: '120mm x3',
    rpmRange: '650 - 2000 RPM',
    noiseLevel: '30 dBA',
    socketSupport: ['LGA1700', 'AM5', 'AM4'],
    dimensions: '394 x 119 x 27.2 mm',
    warranty: '5 Years',
    price: 13999,
    compatibility: 'Desktop',
    description:
      'Triple-fan RGB liquid cooler designed for powerful CPUs with customizable lighting effects.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/coolingSystems/Cooler%20Master%20MasterLiquid%20ML360R%20RGB.jpg?updatedAt=1761832322981',
  },
  {
    id: 8,
    name: 'be quiet! Pure Rock 2 Black',
    brand: 'be quiet!',
    type: 'Air Cooler',
    fanSize: '120mm',
    heatPipes: 4,
    rpmRange: '500 - 1500 RPM',
    noiseLevel: '26.8 dBA',
    socketSupport: ['LGA1700', 'AM5', 'AM4'],
    dimensions: '121 x 87 x 155 mm',
    warranty: '3 Years',
    price: 4299,
    compatibility: 'Desktop',
    description:
      'Silent and efficient air cooler providing solid performance with an elegant black design.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/coolingSystems/be%20quiet!%20Pure%20Rock%202%20Black.jpg?updatedAt=1761832322925',
  },
  {
    id: 9,
    name: 'Lian Li Galahad 360 RGB AIO',
    brand: 'Lian Li',
    type: 'Liquid Cooler (AIO)',
    radiatorSize: '360mm',
    fanSize: '120mm x3',
    rpmRange: '800 - 1900 RPM',
    noiseLevel: '32 dBA',
    socketSupport: ['LGA1700', 'AM5', 'AM4'],
    dimensions: '397.5 x 123.5 x 27 mm',
    warranty: '5 Years',
    price: 13999,
    compatibility: 'Desktop',
    description:
      'Premium 360mm AIO cooler with aluminum housing, sleek RGB effects, and high thermal efficiency.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/coolingSystems/Lian%20Li%20Galahad%20360%20RGB%20AIO.jpg?updatedAt=1761832323033',
  },
  {
    id: 10,
    name: 'Thermaltake TOUGHAIR 510 Air Cooler',
    brand: 'Thermaltake',
    type: 'Air Cooler',
    fanSize: '120mm x2',
    heatPipes: 4,
    rpmRange: '500 - 2000 RPM',
    noiseLevel: '23 dBA',
    socketSupport: ['LGA1700', 'AM5', 'AM4'],
    dimensions: '124 x 107 x 153.4 mm',
    warranty: '3 Years',
    price: 5299,
    compatibility: 'Desktop',
    description:
      'Compact dual-fan air cooler delivering strong thermal performance for gaming and productivity builds.',
    imageUrl:
      'https://ik.imagekit.io/someimages12/E-commerce%20image/coolingSystems/Thermaltake%20TOUGHAIR%20510%20Air%20Cooler.jpg?updatedAt=1761832322849',
  },
];
